# Generated by Django 4.2.2 on 2023-06-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_done',
            field=models.BooleanField(default=False),
        ),
    ]
